// Generated by tool/generate_dtos.py from docs/api/openapi.json 0.4.0.
// Do not edit. Decimal amounts/rates stay exact wire strings; no arithmetic here.

enum AccountType { cash, bank, wallet, card, other }

final class AccountDto {
  const AccountDto({
    required this.name,
    required this.type,
    required this.currency,
    required this.initialBalance,
    required this.color,
    required this.icon,
    required this.sortOrder,
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.deletedAt,
    required this.balance,
    required this.archivedAt,
  });

  final String name;
  final AccountType type;
  final String currency;
  final String initialBalance;
  final String? color;
  final String? icon;
  final int sortOrder;
  final String id;
  final String createdAt;
  final String updatedAt;
  final String? deletedAt;
  final String balance;
  final String? archivedAt;

  factory AccountDto.fromJson(Map<String, Object?> json) {
    _keys(json, <String>{
      'name',
      'type',
      'currency',
      'initial_balance',
      'color',
      'icon',
      'sort_order',
      'id',
      'created_at',
      'updated_at',
      'deleted_at',
      'balance',
      'archived_at',
    }, optional: false);
    return AccountDto(
      name: _string(json, 'name', false)!,
      type: _enum(json, 'type', <String, AccountType>{
        'cash': AccountType.cash,
        'bank': AccountType.bank,
        'wallet': AccountType.wallet,
        'card': AccountType.card,
        'other': AccountType.other,
      }, false)!,
      currency: _string(json, 'currency', false)!,
      initialBalance: _string(json, 'initial_balance', false)!,
      color: _string(json, 'color', true),
      icon: _string(json, 'icon', true),
      sortOrder: json['sort_order'] as int,
      id: _string(json, 'id', false)!,
      createdAt: _string(json, 'created_at', false)!,
      updatedAt: _string(json, 'updated_at', false)!,
      deletedAt: _string(json, 'deleted_at', true),
      balance: _string(json, 'balance', false)!,
      archivedAt: _string(json, 'archived_at', true),
    );
  }
}

enum CategoryKind { income, expense }

enum CategorySystemKey { interestIncome, interestExpense }

final class CategoryDto {
  const CategoryDto({
    required this.name,
    required this.kind,
    required this.parentId,
    required this.icon,
    required this.color,
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.deletedAt,
    required this.isSystem,
    required this.systemKey,
  });

  final String name;
  final CategoryKind kind;
  final String? parentId;
  final String? icon;
  final String? color;
  final String id;
  final String createdAt;
  final String updatedAt;
  final String? deletedAt;
  final bool isSystem;
  final CategorySystemKey? systemKey;

  factory CategoryDto.fromJson(Map<String, Object?> json) {
    _keys(json, <String>{
      'name',
      'kind',
      'parent_id',
      'icon',
      'color',
      'id',
      'created_at',
      'updated_at',
      'deleted_at',
      'is_system',
      'system_key',
    }, optional: false);
    return CategoryDto(
      name: _string(json, 'name', false)!,
      kind: _enum(json, 'kind', <String, CategoryKind>{
        'income': CategoryKind.income,
        'expense': CategoryKind.expense,
      }, false)!,
      parentId: _string(json, 'parent_id', true),
      icon: _string(json, 'icon', true),
      color: _string(json, 'color', true),
      id: _string(json, 'id', false)!,
      createdAt: _string(json, 'created_at', false)!,
      updatedAt: _string(json, 'updated_at', false)!,
      deletedAt: _string(json, 'deleted_at', true),
      isSystem: json['is_system'] as bool,
      systemKey: _enum(json, 'system_key', <String, CategorySystemKey>{
        'interest_income': CategorySystemKey.interestIncome,
        'interest_expense': CategorySystemKey.interestExpense,
      }, true),
    );
  }
}

enum TransactionKind { income, expense, transfer, loan }

enum TransactionStatus { posted, scheduled }

enum TransactionFxRateSource { manual, auto }

enum TransactionSource { web, import, telegram, api }

enum TransactionCategorizationSource { manual, rule, model, llm }

final class TransactionDto {
  const TransactionDto({
    required this.accountId,
    required this.categoryId,
    required this.kind,
    required this.amount,
    required this.currency,
    required this.occurredAt,
    required this.status,
    required this.title,
    required this.note,
    required this.fxRateToBase,
    required this.fxRateSource,
    required this.tagIds,
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.deletedAt,
    required this.transferGroupId,
    required this.recurringRuleId,
    required this.loanId,
    required this.source,
    required this.categorizationSource,
    required this.isInitialData,
    required this.reactivationSuggestions,
  });

  final String accountId;
  final String? categoryId;
  final TransactionKind kind;
  final String amount;
  final String currency;
  final String occurredAt;
  final TransactionStatus status;
  final String title;
  final String? note;
  final String fxRateToBase;
  final TransactionFxRateSource fxRateSource;
  final List<String> tagIds;
  final String id;
  final String createdAt;
  final String updatedAt;
  final String? deletedAt;
  final String? transferGroupId;
  final String? recurringRuleId;
  final String? loanId;
  final TransactionSource source;
  final TransactionCategorizationSource? categorizationSource;
  final bool isInitialData;
  final List<String> reactivationSuggestions;

  factory TransactionDto.fromJson(Map<String, Object?> json) {
    _keys(json, <String>{
      'account_id',
      'category_id',
      'kind',
      'amount',
      'currency',
      'occurred_at',
      'status',
      'title',
      'note',
      'fx_rate_to_base',
      'fx_rate_source',
      'tag_ids',
      'id',
      'created_at',
      'updated_at',
      'deleted_at',
      'transfer_group_id',
      'recurring_rule_id',
      'loan_id',
      'source',
      'categorization_source',
      'is_initial_data',
      'reactivation_suggestions',
    }, optional: false);
    return TransactionDto(
      accountId: _string(json, 'account_id', false)!,
      categoryId: _string(json, 'category_id', true),
      kind: _enum(json, 'kind', <String, TransactionKind>{
        'income': TransactionKind.income,
        'expense': TransactionKind.expense,
        'transfer': TransactionKind.transfer,
        'loan': TransactionKind.loan,
      }, false)!,
      amount: _string(json, 'amount', false)!,
      currency: _string(json, 'currency', false)!,
      occurredAt: _string(json, 'occurred_at', false)!,
      status: _enum(json, 'status', <String, TransactionStatus>{
        'posted': TransactionStatus.posted,
        'scheduled': TransactionStatus.scheduled,
      }, false)!,
      title: _string(json, 'title', false)!,
      note: _string(json, 'note', true),
      fxRateToBase: _string(json, 'fx_rate_to_base', false)!,
      fxRateSource: _enum(
        json,
        'fx_rate_source',
        <String, TransactionFxRateSource>{
          'manual': TransactionFxRateSource.manual,
          'auto': TransactionFxRateSource.auto,
        },
        false,
      )!,
      tagIds: List<String>.unmodifiable(
        (json['tag_ids'] as List<Object?>).cast<String>(),
      ),
      id: _string(json, 'id', false)!,
      createdAt: _string(json, 'created_at', false)!,
      updatedAt: _string(json, 'updated_at', false)!,
      deletedAt: _string(json, 'deleted_at', true),
      transferGroupId: _string(json, 'transfer_group_id', true),
      recurringRuleId: _string(json, 'recurring_rule_id', true),
      loanId: _string(json, 'loan_id', true),
      source: _enum(json, 'source', <String, TransactionSource>{
        'web': TransactionSource.web,
        'import': TransactionSource.import,
        'telegram': TransactionSource.telegram,
        'api': TransactionSource.api,
      }, false)!,
      categorizationSource: _enum(
        json,
        'categorization_source',
        <String, TransactionCategorizationSource>{
          'manual': TransactionCategorizationSource.manual,
          'rule': TransactionCategorizationSource.rule,
          'model': TransactionCategorizationSource.model,
          'llm': TransactionCategorizationSource.llm,
        },
        true,
      ),
      isInitialData: json['is_initial_data'] as bool,
      reactivationSuggestions: List<String>.unmodifiable(
        (json['reactivation_suggestions'] as List<Object?>).cast<String>(),
      ),
    );
  }
}

enum UserIconContentType { imageSvgXml }

final class UserIconDto {
  const UserIconDto({
    required this.id,
    required this.name,
    required this.contentType,
    required this.sizeBytes,
    required this.sha256,
    required this.createdAt,
    required this.updatedAt,
    required this.deletedAt,
  });

  final String id;
  final String name;
  final UserIconContentType contentType;
  final int sizeBytes;
  final String sha256;
  final String createdAt;
  final String updatedAt;
  final String? deletedAt;

  factory UserIconDto.fromJson(Map<String, Object?> json) {
    _keys(json, <String>{
      'id',
      'name',
      'content_type',
      'size_bytes',
      'sha256',
      'created_at',
      'updated_at',
      'deleted_at',
    }, optional: false);
    return UserIconDto(
      id: _string(json, 'id', false)!,
      name: _string(json, 'name', false)!,
      contentType: _enum(json, 'content_type', <String, UserIconContentType>{
        'image/svg+xml': UserIconContentType.imageSvgXml,
      }, false)!,
      sizeBytes: json['size_bytes'] as int,
      sha256: _string(json, 'sha256', false)!,
      createdAt: _string(json, 'created_at', false)!,
      updatedAt: _string(json, 'updated_at', false)!,
      deletedAt: _string(json, 'deleted_at', true),
    );
  }
}

final class TransactionCardPreferencesDto {
  const TransactionCardPreferencesDto({
    this.showDate = true,
    this.showTime = false,
    this.showNote = true,
    this.showTags = true,
    this.showAccount = false,
    this.showActions = false,
  });

  final bool showDate;
  final bool showTime;
  final bool showNote;
  final bool showTags;
  final bool showAccount;
  final bool showActions;

  factory TransactionCardPreferencesDto.fromJson(Map<String, Object?> json) {
    _keys(json, <String>{
      'show_date',
      'show_time',
      'show_note',
      'show_tags',
      'show_account',
      'show_actions',
    }, optional: true);
    return TransactionCardPreferencesDto(
      showDate: _bool(json, 'show_date', true),
      showTime: _bool(json, 'show_time', false),
      showNote: _bool(json, 'show_note', true),
      showTags: _bool(json, 'show_tags', true),
      showAccount: _bool(json, 'show_account', false),
      showActions: _bool(json, 'show_actions', false),
    );
  }

  TransactionCardPreferencesDto copyWith({
    bool? showDate,
    bool? showTime,
    bool? showNote,
    bool? showTags,
    bool? showAccount,
    bool? showActions,
  }) => TransactionCardPreferencesDto(
    showDate: showDate ?? this.showDate,
    showTime: showTime ?? this.showTime,
    showNote: showNote ?? this.showNote,
    showTags: showTags ?? this.showTags,
    showAccount: showAccount ?? this.showAccount,
    showActions: showActions ?? this.showActions,
  );

  Map<String, Object?> toJson() => {
    'show_date': showDate,
    'show_time': showTime,
    'show_note': showNote,
    'show_tags': showTags,
    'show_account': showAccount,
    'show_actions': showActions,
  };
}

T? _enum<T>(
  Map<String, Object?> json,
  String key,
  Map<String, T> values,
  bool nullable,
) {
  final wire = _string(json, key, nullable);
  if (wire == null) return null;
  final value = values[wire];
  if (value == null) throw FormatException('Invalid enum: $key');
  return value;
}

String? _string(Map<String, Object?> json, String key, bool nullable) {
  final value = json[key];
  if (value == null && nullable) return null;
  if (value is! String) throw FormatException('Expected string: $key');
  return value;
}

bool _bool(Map<String, Object?> json, String key, bool fallback) {
  if (!json.containsKey(key)) return fallback;
  final value = json[key];
  if (value is! bool) throw FormatException('Expected boolean: $key');
  return value;
}

void _keys(
  Map<String, Object?> json,
  Set<String> requiredKeys, {
  bool optional = false,
}) {
  if ((!optional && json.length != requiredKeys.length) ||
      !requiredKeys.containsAll(json.keys)) {
    throw const FormatException('Missing or unknown DTO fields');
  }
}
