"""Generate the three spike DTOs from the repository's OpenAPI contract.

No network, templates, or generator dependency. This is deliberately limited to
these flat schemas; the HTTP client belongs to the next phase's base task.
"""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[3]
contract = json.loads((root / 'docs/api/openapi.json').read_text())
schemas = contract['components']['schemas']
lines = [
    '// Generated by tool/generate_dtos.py from docs/api/openapi.json '+contract['info']['version']+'.',
    '// Do not edit. Decimal amounts/rates stay exact wire strings; no arithmetic here.',
    '',
]

def camel(name):
    parts = name.split('_')
    return parts[0] + ''.join(p.title() for p in parts[1:])

for name in ['Account', 'Category', 'Transaction']:
    fields = []
    for key, prop in schemas[name]['properties'].items():
        nullable = 'anyOf' in prop
        if nullable:
            prop = next(p for p in prop['anyOf'] if p.get('type') != 'null')
        enum = prop.get('enum')
        if enum:
            typ = name + camel(key)[0].upper() + camel(key)[1:]
            lines += ['enum '+typ+' { '+', '.join(camel(e) for e in enum)+' }', '']
            # Wire enum names can contain underscores.
            pairs = ', '.join(repr(e)+': '+typ+'.'+camel(e) for e in enum)
            parse = '_enum(json, '+repr(key)+', <String, '+typ+'>{'+pairs+'}, '+str(nullable).lower()+')'+('' if nullable else '!')
        elif prop.get('type') == 'array':
            typ = 'List<String>'
            parse = 'List<String>.unmodifiable((json['+repr(key)+'] as List<Object?>).cast<String>())'
        elif prop.get('type') in ['boolean', 'integer']:
            typ = {'boolean':'bool','integer':'int'}[prop['type']]
            parse = 'json['+repr(key)+'] as '+typ
        else:
            typ = 'String'
            parse = '_string(json, '+repr(key)+', '+str(nullable).lower()+')'+('' if nullable else '!')
        fields.append((key, camel(key), typ+('?' if nullable else ''), parse))
    lines += ['final class '+name+'Dto {', '  const '+name+'Dto({']
    lines += ['    required this.'+f[1]+',' for f in fields]
    lines += ['  });', '']
    lines += ['  final '+f[2]+' '+f[1]+';' for f in fields]
    lines += ['', '  factory '+name+'Dto.fromJson(Map<String, Object?> json) {']
    lines += ['    _keys(json, <String>{'+', '.join(repr(f[0]) for f in fields)+'});']
    lines += ['    return '+name+'Dto(']
    lines += ['      '+f[1]+': '+f[3]+',' for f in fields]
    lines += ['    );', '  }', '}', '']
lines += [
    'T? _enum<T>(Map<String, Object?> json, String key, Map<String, T> values, bool nullable) {',
    '  final wire = _string(json, key, nullable);',
    '  if (wire == null) return null;',
    '  final value = values[wire];',
    "  if (value == null) throw FormatException('Invalid enum: $key');",
    '  return value;',
    '}', '',
    'String? _string(Map<String, Object?> json, String key, bool nullable) {',
    '  final value = json[key];',
    '  if (value == null && nullable) return null;',
    "  if (value is! String) throw FormatException('Expected string: $key');",
    '  return value;',
    '}', '',
    'void _keys(Map<String, Object?> json, Set<String> requiredKeys) {',
    '  if (json.length != requiredKeys.length || !requiredKeys.containsAll(json.keys)) {',
    "    throw const FormatException('Missing or unknown DTO fields');",
    '  }',
    '}',
]
(root / 'apps/web/lib/data/api_dtos.dart').write_text('\n'.join(lines)+'\n')
