"""Generate the typed HTTP subset from the repository OpenAPI (no dependencies).

Wire types/defaults/required fields come from the contract; validation of money,
UUIDs and business constraints remains the server's responsibility.
"""
import json
import re
from pathlib import Path

root = Path(__file__).resolve().parents[3]
contract = json.loads((root / 'docs/api/openapi.json').read_text())
schemas = contract['components']['schemas']
names = ['Account', 'Category', 'Transaction', 'UserIcon', 'TransactionCardPreferences',
         'Tag', 'UserPreferences', 'CurrentUser', 'PasswordLogin', 'AuthenticatedSession',
         'ActionResult', 'UserUpdate', 'FieldError', 'OverpaymentOption', 'Problem',
         'AccountPage', 'CategoryPage', 'TransactionPage', 'TagPage',
         'CurrencyTotal', 'ReportTotal', 'CashFlowRow', 'CategoryReportRow',
         'CashFlowRowPage', 'CategoryReportRowPage', 'BudgetCategoryLimit',
         'Budget', 'Goal', 'BudgetPage', 'GoalPage']
lines = ['// Generated by tool/generate_dtos.py from docs/api/openapi.json '+contract['info']['version']+'.',
         '// Do not edit. Decimal amounts/rates stay exact wire strings; no arithmetic here.', '']

def camel(name):
    parts = re.split(r'[^a-zA-Z0-9]+', name)
    return parts[0] + ''.join(p.title() for p in parts[1:])

def type_for(prop):
    if '$ref' in prop:
        target = prop['$ref'].split('/')[-1]
        return target+'Dto' if target in names else type_for(schemas[target])
    return {'string': 'String', 'boolean': 'bool', 'integer': 'int'}[prop['type']]

for name in names:
    fields = []
    nonnullable = []
    required = set(schemas[name].get('required', []))
    for key, prop in schemas[name]['properties'].items():
        wire_nullable = 'anyOf' in prop
        if wire_nullable:
            prop = next(p for p in prop['anyOf'] if p.get('type') != 'null')
        if not wire_nullable: nonnullable.append(key)
        optional = key not in required
        default = None
        if optional and prop.get('type') == 'boolean' and 'default' in prop:
            default = str(prop['default']).lower()
        # RF-47 is the only schema whose explicit defaults must be materialized.
        if name == 'UserPreferences' and key == 'transaction_card':
            default = 'const TransactionCardPreferencesDto()'
        nullable = wire_nullable or (optional and default is None)
        enum = prop.get('enum')
        field = camel(key)
        access = 'json['+repr(key)+']'
        if enum:
            typ = name + field[0].upper() + field[1:]
            lines += ['enum '+typ+' { '+', '.join(camel(e) for e in enum)+' }', '']
            pairs = ', '.join(repr(e)+': '+typ+'.'+camel(e) for e in enum)
            parse = '_enum('+access+', '+repr(key)+', <String, '+typ+'>{'+pairs+'}, '+str(nullable).lower()+')'+('' if nullable else '!')
            serial = '{'+', '.join(typ+'.'+camel(e)+': '+repr(e) for e in enum)+'}['+field+']'
        elif prop.get('type') == 'array':
            item = type_for(prop['items'])
            typ = 'List<'+item+'>'
            parse = 'List<'+item+'>.unmodifiable(('+access+' as List<Object?>).map((value) => '+(item+'.fromJson(_object(value))' if item.endswith('Dto') else 'value as '+item)+'))'
            serial = field+('.map((value) => value.toJson()).toList()' if item.endswith('Dto') else '')
        else:
            typ = type_for(prop)
            if typ.endswith('Dto'):
                parse = typ+'.fromJson(_object('+access+'))'
                serial = field+('?' if nullable else '')+'.toJson()'
            else:
                parse = '_value<'+typ+'>('+access+', '+repr(key)+', '+str(nullable).lower()+')'+('' if nullable else '!')
                serial = field
        if nullable and typ.startswith('List'):
            parse = access+' == null ? null : '+parse
            if serial != field:
                serial = serial.replace(field+'.', field+'?.', 1)
        elif nullable and typ.endswith('Dto'):
            parse = access+' == null ? null : '+parse
        if default is not None:
            parse = '(json.containsKey('+repr(key)+') ? '+parse+' : '+default+')'
        fields.append((key, field, typ+('?' if nullable else ''), parse, serial, optional, default))
    lines += ['final class '+name+'Dto {', '  const '+name+'Dto({']
    lines += ['    '+('required ' if not f[5] else '')+'this.'+f[1]+(' = '+f[6] if f[6] else '')+',' for f in fields]
    lines += ['  });', '']
    lines += ['  final '+f[2]+' '+f[1]+';' for f in fields]
    lines += ['', '  factory '+name+'Dto.fromJson(Map<String, Object?> json) {',
              '    _keys(json, {'+', '.join(repr(f[0]) for f in fields)+'}, {'+', '.join(repr(k) for k in sorted(required))+'}, {'+', '.join(repr(k) for k in nonnullable)+'});',
              '    return '+name+'Dto(']
    lines += ['      '+f[1]+': '+f[3]+',' for f in fields]
    lines += ['    );', '  }']
    if name in ['TransactionCardPreferences', 'UserPreferences']:
        lines += ['', '  '+name+'Dto copyWith({']
        lines += ['    '+f[2].rstrip('?')+'? '+f[1]+',' for f in fields]
        lines += ['  }) => '+name+'Dto(']
        lines += ['    '+f[1]+': '+f[1]+' ?? this.'+f[1]+',' for f in fields]
        lines += ['  );']
    lines += ['', '  Map<String, Object?> toJson() => {']
    for f in fields:
        serial = f[4]
        if name == 'UserPreferences':
            if f[0] == 'theme': serial += " ?? 'system'"
            if f[0] == 'home_widgets': serial += ' ?? const <String>[]'
        condition = 'if ('+f[1]+' != null) ' if f[5] and f[6] is None and name != 'UserPreferences' else ''
        lines += ['    '+condition+repr(f[0])+': '+serial+',']
    lines += ['  };', '}', '']
lines += [
    'T? _value<T>(Object? value, String key, bool nullable) {',
    '  if (value == null && nullable) return null;',
    "  if (value is! T) throw FormatException('Invalid field type: $key');",
    '  return value;', '}', '',
    'Map<String, Object?> _object(Object? value) => (value as Map<String, Object?>);', '',
    'T? _enum<T>(Object? wire, String key, Map<String, T> values, bool nullable) {',
    '  if (wire == null && nullable) return null;',
    '  final value = values[wire];',
    "  if (value == null) throw FormatException('Invalid enum: $key');", '  return value;', '}', '',
    'void _keys(Map<String, Object?> json, Set<String> allowed, Set<String> required, Set<String> nonnullable) {',
    '  if (!allowed.containsAll(json.keys) || !json.keys.toSet().containsAll(required) || nonnullable.any((key) => json.containsKey(key) && json[key] == null)) {',
    "    throw const FormatException('Missing or unknown DTO fields');", '  }', '}',
]
(root / 'apps/web/lib/data/api_dtos.dart').write_text('\n'.join(lines)+'\n')
